// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbevifhkdpjacnbwxvkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZXZpZmhrZHBqYWNuYnd4dmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTI3NTUsImV4cCI6MjA3MDg4ODc1NX0.4D-K8lC12KvYb5HFe7C8DjnF-fkHQBYiW4oZhp_YsXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});